package type1

const (
	BlueFuzz                 = "BlueFuzz"
	BlueScale                = "BlueScale"
	BlueShift                = "BlueShift"
	BlueValues               = "BlueValues"
	ExpansionFactor          = "ExpansionFactor"
	FamilyBlues              = "FamilyBlues"
	FamilyOtherBlues         = "FamilyOtherBlues"
	ForceBold                = "ForceBold"
	LanguageGroup            = "LanguageGroup"
	Len4                     = "lenIV"
	MinFeature               = "MinFeature"
	NoAccessDef              = "ND"
	NoAccessDefAlt           = "|-"
	NoAccessPut              = "NP"
	NoAccessPutAlt           = "|"
	OtherBlues               = "OtherBlues"
	OtherSubroutines         = "OtherSubrs"
	Password                 = "password"
	RdProcedure              = "RD"
	RdProcedureAlt           = "-|"
	RndStemUp                = "RndStemUp"
	StdHorizontalStemWidth   = "StdHW"
	StdVerticalStemWidth     = "StdVW"
	StemSnapHorizontalWidths = "StemSnapH"
	StemSnapVerticalWidths   = "StemSnapV"
	Subroutines              = "Subrs"
	UniqueId                 = "UniqueID"
	Erode                    = "Erode"
)
